name = "LatPhysBase"
uuid = "eec5c15a-e8bd-11e8-0d23-6799ca40c963"
authors = ["Jan Attig <jattig@thp.Uni-Koeln.DE>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
